function(matrix_require_file cell path)
    if (NOT EXISTS "${path}")
        message(FATAL_ERROR "${cell}: required artifact is absent: ${path}")
    endif ()
endfunction()

function(matrix_require_no_file cell path)
    if (EXISTS "${path}")
        message(FATAL_ERROR "${cell}: ${path} exists, and this cell is only meaningful without it")
    endif ()
endfunction()

function(matrix_require_cache cell build pattern)
    matrix_require_file("${cell}" "${build}/CMakeCache.txt")
    file(STRINGS "${build}/CMakeCache.txt" matched REGEX "${pattern}")
    if (NOT matched)
        message(FATAL_ERROR "${cell}: no cache entry matching '${pattern}' in ${build}/CMakeCache.txt")
    endif ()
endfunction()

function(matrix_require_text cell label text pattern)
    if (NOT text MATCHES "${pattern}")
        message(FATAL_ERROR "${cell}: ${label} does not contain '${pattern}'")
    endif ()
endfunction()

function(matrix_require_no_text cell label text pattern)
    if (text MATCHES "${pattern}")
        message(FATAL_ERROR "${cell}: ${label} contains '${pattern}', which must not reach it")
    endif ()
endfunction()

# Located by search rather than by a hard-coded lib/cmake/<name>: CMAKE_INSTALL_LIBDIR
# varies by platform, and the count assertion is what turns an install that created
# nothing into a failure instead of a silent pass.
function(matrix_package_dir cell prefix package out)
    file(GLOB_RECURSE found "${prefix}/${package}Config.cmake")
    list(LENGTH found count)
    if (NOT count EQUAL 1)
        message(FATAL_ERROR
            "${cell}: expected exactly one ${package}Config.cmake under ${prefix}, found ${count}")
    endif ()
    get_filename_component(directory "${found}" DIRECTORY)
    set(${out} "${directory}" PARENT_SCOPE)
endfunction()

function(matrix_version_compatible file version out)
    set(PACKAGE_FIND_VERSION "${version}")
    string(REGEX MATCHALL "[0-9]+" parts "${version}")
    list(GET parts 0 PACKAGE_FIND_VERSION_MAJOR)
    list(GET parts 1 PACKAGE_FIND_VERSION_MINOR)
    list(GET parts 2 PACKAGE_FIND_VERSION_PATCH)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
    include("${file}")
    set(${out} ${PACKAGE_VERSION_COMPATIBLE} PARENT_SCOPE)
endfunction()

function(matrix_require_compatibility cell file version accepted)
    matrix_version_compatible("${file}" "${version}" verdict)
    if (verdict AND NOT accepted)
        message(FATAL_ERROR "${cell}: the installed package accepts a request for ${version}, "
            "which is wider than the compatibility policy it declares")
    endif ()
    if (accepted AND NOT verdict)
        message(FATAL_ERROR "${cell}: the installed package rejects a request for ${version}, "
            "which the compatibility policy it declares must accept")
    endif ()
endfunction()

# The version file decides whether find_package(cartan <version>) resolves at all, so its
# absence is invisible to every other assertion here. A request for an older patch and a
# request for an older minor are what separate the declared policy from the three
# neighbouring ones: a higher minor is rejected by all of them and discriminates nothing.
function(matrix_require_version cell package_dir)
    set(file "${package_dir}/cartanConfigVersion.cmake")
    matrix_require_file("${cell}" "${file}")
    include("${file}")
    string(REGEX MATCHALL "[0-9]+" parts "${PACKAGE_VERSION}")
    list(GET parts 0 major)
    list(GET parts 1 minor)
    matrix_require_compatibility("${cell}" "${file}" "${PACKAGE_VERSION}" TRUE)
    matrix_require_compatibility("${cell}" "${file}" "${major}.${minor}.0" TRUE)
    if (minor GREATER 0)
        math(EXPR older "${minor} - 1")
        matrix_require_compatibility("${cell}" "${file}" "${major}.${older}.0" FALSE)
    endif ()
endfunction()

function(matrix_require_export cell prefix enabled)
    matrix_package_dir("${cell}" "${prefix}" cartan package_dir)
    matrix_require_file("${cell}" "${prefix}/include/cartan/version.h")
    matrix_require_file("${cell}" "${package_dir}/cartanTargets.cmake")
    matrix_require_version("${cell}" "${package_dir}")
    file(READ "${package_dir}/cartanTargets.cmake" exported)
    set(label "the installed export set")
    foreach (backend IN LISTS CARTAN_OPTIONAL_BACKENDS)
        string(TOUPPER "${backend}" upper)
        if (backend IN_LIST enabled)
            matrix_require_text("${cell}" "${label}" "${exported}" "cartan::${backend}")
            matrix_require_text("${cell}" "${label}" "${exported}" "CARTAN_HAS_${upper}=1")
            matrix_require_text("${cell}" "${label}" "${exported}" "${CARTAN_${upper}_TARGET}")
        else ()
            matrix_require_no_text("${cell}" "${label}" "${exported}" "CARTAN_HAS_${upper}")
        endif ()
    endforeach ()
endfunction()
