function(matrix_require_file cell path)
    if (NOT EXISTS "${path}")
        message(FATAL_ERROR "${cell}: required artifact is absent: ${path}")
    endif ()
endfunction()

function(matrix_require_no_file cell path)
    if (EXISTS "${path}")
        message(FATAL_ERROR "${cell}: ${path} exists, and this cell is only meaningful without it")
    endif ()
endfunction()

function(matrix_require_cache cell build pattern)
    matrix_require_file("${cell}" "${build}/CMakeCache.txt")
    file(STRINGS "${build}/CMakeCache.txt" matched REGEX "${pattern}")
    if (NOT matched)
        message(FATAL_ERROR "${cell}: no cache entry matching '${pattern}' in ${build}/CMakeCache.txt")
    endif ()
endfunction()

function(matrix_require_text cell label text pattern)
    if (NOT text MATCHES "${pattern}")
        message(FATAL_ERROR "${cell}: ${label} does not contain '${pattern}'")
    endif ()
endfunction()

function(matrix_require_no_text cell label text pattern)
    if (text MATCHES "${pattern}")
        message(FATAL_ERROR "${cell}: ${label} contains '${pattern}', which must not reach it")
    endif ()
endfunction()

# Located by search rather than by a hard-coded lib/cmake/<name>: CMAKE_INSTALL_LIBDIR
# varies by platform, and the count assertion is what turns an install that created
# nothing into a failure instead of a silent pass.
function(matrix_package_dir cell prefix package out)
    file(GLOB_RECURSE found "${prefix}/${package}Config.cmake")
    list(LENGTH found count)
    if (NOT count EQUAL 1)
        message(FATAL_ERROR
            "${cell}: expected exactly one ${package}Config.cmake under ${prefix}, found ${count}")
    endif ()
    get_filename_component(directory "${found}" DIRECTORY)
    set(${out} "${directory}" PARENT_SCOPE)
endfunction()

function(matrix_require_export cell prefix enabled)
    matrix_package_dir("${cell}" "${prefix}" cartan package_dir)
    matrix_require_file("${cell}" "${prefix}/include/cartan/version.h")
    matrix_require_file("${cell}" "${package_dir}/cartanTargets.cmake")
    file(READ "${package_dir}/cartanTargets.cmake" exported)
    set(label "the installed export set")
    foreach (backend IN LISTS CARTAN_OPTIONAL_BACKENDS)
        string(TOUPPER "${backend}" upper)
        if (backend IN_LIST enabled)
            matrix_require_text("${cell}" "${label}" "${exported}" "cartan::${backend}")
            matrix_require_text("${cell}" "${label}" "${exported}" "CARTAN_HAS_${upper}=1")
            matrix_require_text("${cell}" "${label}" "${exported}" "${CARTAN_${upper}_TARGET}")
        else ()
            matrix_require_no_text("${cell}" "${label}" "${exported}" "CARTAN_HAS_${upper}")
        endif ()
    endforeach ()
endfunction()
