cmake_minimum_required(VERSION 3.28)

# Everything after `--` on a `cmake -P` line, so one invocation of this script
# serves every platform without a shell wrapper per host.
set(recipe_arguments "")
set(recipe_after_separator FALSE)
math(EXPR recipe_last_argument "${CMAKE_ARGC} - 1")
foreach (index RANGE 1 ${recipe_last_argument})
    set(token "${CMAKE_ARGV${index}}")
    if (recipe_after_separator)
        list(APPEND recipe_arguments "${token}")
    elseif (token STREQUAL "--")
        set(recipe_after_separator TRUE)
    endif ()
endforeach ()

set(RECIPE_REPO_ROOT "")
set(RECIPE_OUT "")
set(RECIPE_MODE "")
set(RECIPE_OVERRIDE "")
set(RECIPE_TIMEOUT 1800)
set(RECIPE_BLOCK_SYSTEM_DEPENDENCY FALSE)

while (recipe_arguments)
    list(POP_FRONT recipe_arguments token)
    if (token STREQUAL "--no-system-dependency")
        set(RECIPE_BLOCK_SYSTEM_DEPENDENCY TRUE)
    elseif (token MATCHES "^--(repo-root|out|mode|recipe-override|timeout)$")
        if (NOT recipe_arguments)
            message(FATAL_ERROR "consumability: ${token} needs a value")
        endif ()
        string(REGEX REPLACE "^--(recipe-)?" "" setting "${token}")
        string(REPLACE "-" "_" setting "${setting}")
        string(TOUPPER "${setting}" setting)
        list(POP_FRONT recipe_arguments value)
        set(RECIPE_${setting} "${value}")
    else ()
        message(FATAL_ERROR "consumability: unknown argument '${token}'")
    endif ()
endwhile ()

if (NOT IS_DIRECTORY "${RECIPE_REPO_ROOT}")
    message(FATAL_ERROR "consumability: --repo-root must name the cartan source tree, got '${RECIPE_REPO_ROOT}'")
endif ()
if (NOT RECIPE_OUT)
    message(FATAL_ERROR "consumability: --out must name a scratch directory outside the repository")
endif ()
if (NOT RECIPE_MODE MATCHES "^(published|working-tree|coordinates)$")
    message(FATAL_ERROR "consumability: --mode must be published, working-tree or coordinates, got '${RECIPE_MODE}'")
endif ()
file(GLOB recipe_out_entries "${RECIPE_OUT}/*")
if (recipe_out_entries)
    message(FATAL_ERROR "consumability: --out '${RECIPE_OUT}' is not empty; refusing to delete a directory this run did not create")
endif ()
get_filename_component(RECIPE_REPO_ROOT "${RECIPE_REPO_ROOT}" REALPATH)
get_filename_component(RECIPE_OUT "${RECIPE_OUT}" ABSOLUTE)
string(FIND "${RECIPE_OUT}" "${RECIPE_REPO_ROOT}/" recipe_out_inside_repository)
if (recipe_out_inside_repository EQUAL 0)
    message(FATAL_ERROR "consumability: --out lies inside the repository; the harness writes nothing there")
endif ()

find_program(RECIPE_PYTHON NAMES python3 python REQUIRED)
find_program(RECIPE_GIT NAMES git REQUIRED)

include("${CMAKE_CURRENT_LIST_DIR}/recipe_extract.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/recipe_consumer.cmake")

file(MAKE_DIRECTORY "${RECIPE_OUT}")

if (RECIPE_OVERRIDE)
    message(STATUS "consumability: running an out-of-band body from '${RECIPE_OVERRIDE}' rather than the emitted set")
    get_filename_component(recipe_override_label "${RECIPE_OVERRIDE}" NAME_WE)
    set(recipe_selected "${recipe_override_label}=${RECIPE_OVERRIDE}")
else ()
    recipe_select(recipe_selected)
endif ()

list(LENGTH recipe_selected recipe_count)
if (recipe_count LESS 1)
    message(FATAL_ERROR "consumability: no recipe to consume; a harness that runs nothing is not a gate")
endif ()
message(STATUS "consumability: mode ${RECIPE_MODE}, ${recipe_count} recipe(s) to consume")

foreach (entry IN LISTS recipe_selected)
    string(REGEX REPLACE "=.*$" "" label "${entry}")
    string(REGEX REPLACE "^[^=]*=" "" body_path "${entry}")
    recipe_assert_coordinates("${label}" "${body_path}")
    if (NOT RECIPE_MODE STREQUAL "coordinates")
        recipe_consume("${label}" "${body_path}")
    endif ()
endforeach ()

file(REMOVE_RECURSE "${RECIPE_OUT}")
message(STATUS "consumability: ${recipe_count} recipe(s) passed in ${RECIPE_MODE} mode; scratch tree removed")
